# Java8 Alpine Release
FROM frolvlad/alpine-oraclejdk8:slim
# configure WorkDir
WORKDIR /app
# Mount HOST Folder 
VOLUME /app
# Copy Spring Boot File to target
COPY artifact/boot-0.0.1-SNAPSHOT.jar /app/boot-0.0.1-SNAPSHOT.jar
#Expose Ports - ONLY EXPOSED - IT’S NOT Mapped. -p will be needed on run
EXPOSE 8080
# Command to run (Entry Point)
CMD java -jar -Dspring.profiles.active=test /app/boot-0.0.1-SNAPSHOT.jar
