ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
#RUN elasticsearch-plugin install ingest-user-agent
#RUN elasticsearch-plugin install ingest-geoip
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
